export default {
    LOAD_GAMES: 'LOAD_GAMES',
    LOAD_GAME: 'LOAD_GAME',
    ADD_GAME: 'ADD_GAME',
    EDIT_GAME: 'EDIT_GAME',
    DELETE_GAME: 'DELETE_GAME',
    LOAD_ASSISTANTS: 'LOAD_ASSISTANTS',
    LOAD_ASSISTANT: 'LOAD_ASSISTANT',
    ADD_ASSISTANT: 'ADD_ASSISTANT',
    EDIT_ASSISTANT: 'EDIT_ASSISTANT',
    DELETE_ASSISTANT: 'DELETE_ASSISTANT',
}

