import {combineReducers} from 'redux';

export default {
    GET_GAMES: 'GET_GAMES',
    GET_GAME: 'GET_GAME',
    ADD_GAME: 'ADD_GAME',
    EDIT_GAME: 'EDIT_GAME',
    DELETE_GAME: 'DELETE_GAME',
    GET_ASSITANTS: 'GET_ASSITANTS',
    GET_ASSITANT: 'GET_ASSITANT',
    ADD_ASSITANT: 'ADD_ASSITANT',
    EDIT_ASSITANT: 'EDIT_ASSITANT',
    DELETE_ASSITANT: 'DELETE_ASSITANT',
}

